### ISSUE TITLE
splash screen while data is loaded

### ISSUE THREAD

**Issue by BigEd** [hoglet67/hoglet67.github.io#1]
For the first run, there's a 20M file to be loaded into cache, which could cause quite a delay depending on the user's connection.  It would be good to show some indication of the site not being broken.

It's possible to add a single `<div>` to the `<body>` in the index.html above the `<canvas>` - possibly not the best way but it does seem to work:
```
...
<body>
<div style='color:green;font-size:xx-large;font-family:courier'>Loading Atom emulator: please wait ...</div>
<canvas ...

```

**Comment by BigEd** [comment]
A bit nicer.  I took a screenshot of the Atom screen displaying a Loading... please wait message, and then put this div into the top of the body instead:
`<div style='height:100vh; background-position:center; background-repeat:no-repeat; background-image:url("Loading-screen.png");></div>
`

If that image were an animated GIF it could even show a fake progress bar...

**Comment by hoglet67** [comment]
There are actually real procress event callbacks, that might be usable.  Check the console log when loading.

**Comment by BigEd** [comment]
Indeed - I had a go hacking at the JS, didn't try to do it properly. It looks like there are chained tasks with dependencies, so one could put one ahead of data loading and one after.  If for any reason it's not clean to modify the index.html, it would be possible to insert or modify a DIV in JS.

**Comment by BigEd** [comment]
As we had some success today updating the upstream template file, I'll close this
